### ISSUE TITLE
Broken Reset Button

### ISSUE THREAD

**Issue by mkoe-unitb** [djuric/change-last-modified-date#23]
When I click on "reset" within the dropdown I get an "invalid date" in the button and the date will saved as 01.01.1970.

It could be fixed when you insert the `currentModified` into the `currentModified`-method and set an fallback to `modified`:

      currentModified(modified, currentModified) {

        if(!modified) {
          modified = currentModified;
        }

        document
          .getElementById('clm-modified-date')
          .setAttribute('value', modified);
        dispatch('core/editor').editPost({ modified });
      },

And in the DateTimePicker:

`onChange={(modified) => handleModified(modified, currentModified)}`

Or is something else expected?

**Comment by djuric** [comment]
Hello,

Thanks for reporting this, `reset` button was indeed setting "invalid date". 

In latest version this button is deprecated https://developer.wordpress.org/block-editor/reference-guides/components/date-time/#__nextremoveresetbutton-boolean, I have now released a new plugin version and added the props that will hide it by default.
