### ISSUE TITLE
Gutenberg crashing in CPT

### ISSUE THREAD

**Issue by rudyportillo101** [djuric/change-last-modified-date#5]
Hey first of great plugin!

I noticed an issue with the Gutenberg editor were it crashes on any CPT new/edit screen.

![Screen Shot 2020-10-26 at 5 11 45 PM](https://user-images.githubusercontent.com/31315955/97241447-5f90b700-17ae-11eb-916c-b2aea3f3ff55.png)

It would be great to prevent this issue even if the CPT is not defined in the wp-config.php file.

**Comment by djuric** [comment]
Thanks for raising this issue.

It has been fixed now, problem was with custom post types which didn't have custom fields support declared. Updating to 1.4.2 will fix it.
